In [ ]:
               '''      """            Python Libarires for Machine Learning      """      '''

# Numpy Module ---> * It is a module for Numerical Python and is the Core Library for numeric scientific computing .
                    * It Consists Multi Dimensional Array objects and a Collection of routines for processing those arrays.

In [1]:
# 1.

import numpy as np

Single_dimensional_Array = np.array([10,20,30,40,50])
Single_dimensional_Array


array([10, 20, 30, 40, 50])

In [4]:
# To Check the Array Type.

type(Single_dimensional_Array)

numpy.ndarray

In [3]:
# 2.

import numpy as np

Multi_dimensional_Array = np.array([[10,20,30,50], [11,22,33,44]])
Multi_dimensional_Array


array([[10, 20, 30, 50],
       [11, 22, 33, 44]])

In [ ]:

                                  """    Initializing Numpy Array With Zeros    """

In [11]:
# 1. """ Zeros with rows and columns """

import numpy as np 
n1 = np.zeros((1,2))

# For Multi Dimentional Array.
n2 = np.zeros((5,5))

n1 , n2

(array([[0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [40]:
# 2. """ Creating the Multi Dimentional Array by Random .  """
""" @--> Here random.rand is Key Function for random inputs to Array """

import numpy as np
n1 = np.random.rand(4,5)
n1

""" @--> random.randint is used for creating the array from the n to m range by skiping a values by smae distance """
import numpy as np
n2 = np.random.randint(10,100,15)

n1 , n2

(array([[0.39444357, 0.59641913, 0.31682005, 0.73448851, 0.82534612],
        [0.8692026 , 0.19830736, 0.66429017, 0.65385351, 0.43308317],
        [0.73378592, 0.4699844 , 0.85426012, 0.01532981, 0.06746639],
        [0.05180809, 0.66266632, 0.53004146, 0.75957364, 0.89680681]]),
 array([11, 66, 15, 30, 84, 89, 13, 24, 83, 55, 67, 40, 88, 48, 19]))

In [31]:
# 2.1   """ Intalizing the Numpy Array with a Range """

import numpy as np

n3 = np.arange(10,18)


""" In this one while  creating we can step the number particular distance """

n4 = np.arange(20,80,5)
n3  , n4

(array([10, 11, 12, 13, 14, 15, 16, 17]),
 array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75]))

In [34]:
# 2.2 """ filling the Same  number  by n X m Array . """

import numpy as np

n5 = np.full((3,4),5)
n5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# 3. """ To take a n by m array input by user input using NumPy """

import numpy as np

# Get the number of rows and columns from the user.
n = int(input("Enter the number of rows: "))
m = int(input("Enter the number of columns: "))

# Create an empty array.
array = np.empty((n, m))

# Get the array elements from the user.
for i in range(n):
    for j in range(m):
        array[i, j] = int(input("Enter the element at row {} column {}: ".format(i, j)))

# Print the array.
print(array)


In [50]:
# 4. """ Checking the Numpy Array """
""" @--> Here to check the numpy array Dimensions / Shape """
import numpy as np
n6 = n1.shape # Here Iam taking the direct above n1 array.
n6

# 4.1 reshape the Array 
""" @--> While reshaping a Matrix it's only possible when m != n """
n7=np.array([[1,2,3],[4,5,6]])
n7.shape
n7.shape = (3,2) 
n7.shape

(3, 2)

In [57]:
# 5. """ Joining a Array's """

# 5.1  """ vstack() which is vertical | join the arrays  """
""" @--> here we joining the arrays Vertically """
import numpy as np 
n8 = np.array([1,2,3])
n9 = np.array([4,5,6])

np.vstack((n8,n9))

# 5.2  """ hstack() which is  horizontal --  joining the arrays """

""" @--> here we joing the arrays horizontally """
np.hstack((n8,n9))

# 5.3  """ column_stack () """
""" @--> here we joing the arrays two arrays , 
In this the function will be like alla the columns are add and form as a row """

import numpy as np
np.column_stack((n8,n9))


array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy array Intersection & Difference 

In [4]:
# 6 . """ Intersection """
""" @--> Here we are using intersect1d , it is keyword for intersection b/w arrays .
its give output as elements same in all the given arrays ."""

import numpy as np

n1 = np.array([10,20,30,40])
n2 = np.array([20,40,30,50])
np.intersect1d(n1,n2) """ @--> Here 1d is a one dimensional its represent the output in one dimensional array """



array([20, 30, 40])

In [14]:
# 7 . """  Difference  """

""" @--> Here we are getting the output which is not same elements consists in a  given arrays ..
Here we use keyword is setdiff1d . """

import numpy as np

n3 = np.array([12,34,56,78])
n4 = np.array([34,21,65,87])
np.setdiff1d(n3,n4)
"""@--> ( Here n3 is comparing with n4 and removing the same elements in arrays then given output as remaining n3 consists elements """

np.setdiff1d(n4,n3)
"""@--> here also same process as a above Funtionality but here n4 is comparing with n3 and avoiding the same elements consists in two arrays , given output as remaing the n4 elements """


array([21, 65, 87])

                               """       Numpy Array MatheMatics       """

# Numpy Array Sum 

In [26]:
# 8 . Addition Of Numpy Arrays 

import numpy as np

n5 = np.array([11,20,10])
n6 = np.array([24,12,20])

np.sum([n5,n6])
""" this directly give the total sum of the array elements """
''' For a proper Array sum we must give the axis '''
# # 8.1 
""" if axis = 0  , Here its add the columns elements of the array """
np.sum([n5,n6],axis=0)

""" if axis = 1  , here its add the  elemnts in a row  """
np.sum([n5,n6],axis=1)

array([41, 56])

# Basic Numpy Array MatheMatical Opertions 

In [27]:
# Basic Addition 
import numpy as np
n7 = np.array([10,20,30])
n7 = n7+1 """ by adding 1 from the all elements in a array """
n7

array([11, 21, 31])

In [28]:
# Basic Subtraction
import numpy as np
n8 = np.array([10,20,30])
n8 = n8-1 """ Here by Subtracting 2 from the all elements in a array """
n8

array([ 9, 19, 29])

In [29]:
# Basic Multiplication
import numpy as np
n9 = np.array([10,20,30])
n9 = n9*10
n9

array([100, 200, 300])

In [30]:
# Basic Division 
import numpy as np
n10 = np.array([10,20,50])
n10 = n10/5
n10

array([ 2.,  4., 10.])

# 9 Numpy Array Mathematical Functions

In [31]:
# 9.1 Mean 

import numpy as np
n11 = np.array([10,30,57,89,90])
np.mean(n11)

55.2

In [33]:
# 9.2 Median

import numpy as np
n12 = np.array([12,30,57,89,90])
np.median(n12)


57.0

In [34]:
# 9.3 Standard Deviation

import numpy as np
n13 = np.array([12,30,57,889,90])
np.std(n13)

337.726871895027

# Numpy Matrix

In [35]:
# Creating the Matrix using Numpy Array

import numpy as np
n14 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n14

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
""" @--> Access the elements from the matrix using index of the array """
n14[0] 

array([1, 2, 3])

In [37]:
n14[1]

array([4, 5, 6])

In [46]:
""" @--> Here we Aceesing the elements of Matrix by calling the index value of a Array"""
n14[1] '--> it gives the index 1 elements in an array'

array([4, 5, 6])

In [49]:
n14[:3] """ @--> Here [ _Starting index  : _ ending index ] we giving the range of index from start to end to get the index vales in b/w range """


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
n14[:,2] """ @--> Here , we use its indecates that supparates the rows and columns . which gives the [Row , column] of data """


array([3, 6, 9])

In [52]:
""" Same As """
n14[:,1]

array([2, 5, 8])

In [54]:
""" If we want an Elemnt of paricular row of column """
n14[1][2] """ @--> Here the index arestarting from zero both row and column """

6

# Numpy Array Transpose

In [55]:
""" Transpose is nothing but to interchange the rows and columns """
""" @--> transpose() """

n14

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
""" by the above matrix we are performing the Transpose """
n14.transpose()


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Numpy Array Multiplication 

In [68]:
""" @--> Creating a Two Matrix """
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

print(" Matrix a ")
a

 Matrix a 


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
print(" Matrix b ")
b

 Matrix b 


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [69]:
""" For a X b Matrix """
print(" a X b Matrix ")
a.dot(b)


 a + b Matrix 


array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [70]:
""" For b X a Matrix """
print(" b X a ")
b.dot(a)

 b + a 


array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

# Numpy Array Save And Load

In [1]:
# Save 
import numpy as np

n1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
np.save('NumpyArray_SaveFile',n1) # @--> here we are Saving the array data in the file by giving the  np.save(filename , array)

In [2]:
#load 
import numpy as np

n2 = np.load('NumpyArray_SaveFile.npy')
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])